server:
  ip: 120.78.66.15
  #ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.66.15:3306/crm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 你的邮箱地址
    username: 1796733214@qq.com
    # 授权码
    password: bmlhnpaymipqbjbf
    # 编码格式
    default-encoding: utf-8
    # 协议
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          # 部署到服务器后配置
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    # 端口
    port: 465

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    #path: D:/CRM/files/
    path: /home/files/
